SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME REGEXP 'Milk|Yogurt'
    GROUP BY CART_ID
      HAVING COUNT(DISTINCT NAME) >= 2
    ORDER BY 1;
    














# SELECT CART_ID
#     FROM (SELECT CART_ID
#             FROM CART_PRODUCTS
#             GROUP BY CART_ID, NAME
#             HAVING NAME REGEXP 'Milk|Yogurt') AS S
#     GROUP BY CART_ID
#       HAVING COUNT(CART_ID) = 2