SELECT HOUR(DATETIME) AS 'HOUR', COUNT(DATETIME) AS 'COUNT'
    FROM ANIMAL_OUTS 
    WHERE HOUR(DATETIME) BETWEEN 9 AND 19
    GROUP BY HOUR(DATETIME)
    ORDER BY HOUR



















# -- SUBSTRING 사용.

# # SELECT SUBSTRING(DATETIME, 12, 2) AS HOUR
# #         , COUNT(*) AS 'COUNT'
# #     FROM ANIMAL_OUTS
# #     GROUP
# #        BY HOUR
# #     HAVING HOUR BETWEEN 9 AND 19
# #     ORDER BY HOUR


# -- DATE_FORMAT 사용.

# SELECT DATE_FORMAT(DATETIME,'%H') AS HOUR,
#         COUNT(*) AS 'COUNT'
#     FROM ANIMAL_OUTS
#     GROUP
#        BY HOUR
#     HAVING HOUR BETWEEN 9 AND 19
#     ORDER BY HOUR


# -- DATEPART 막힘.
# # SELECT DATEPART(HH,'2016-06-12 11:46:00')
# #     FROM ANIMAL_OUTS