-- 코드를 입력하세요
SELECT SUBSTRING(DATETIME, 12, 2) AS HOUR

        , COUNT(*) AS 'COUNT'
    FROM ANIMAL_OUTS
    GROUP
       BY HOUR
    HAVING HOUR BETWEEN 9 AND 19
    ORDER BY HOUR



-- DATEPART 막힘.
# SELECT DATEPART(HH,'2016-06-12 11:46:00')
#     FROM ANIMAL_OUTS