SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
    FROM (SELECT *
            FROM FOOD_PRODUCT
            WHERE CATEGORY IN ('과자','국','김치','식용유')) P1
    WHERE PRICE = (SELECT MAX(PRICE)
                    FROM FOOD_PRODUCT P2
                    WHERE P1.CATEGORY = P2.CATEGORY)
    ORDER BY 2 DESC
    





















# SELECT F2.CATEGORY, F2.MAX_PRICE, PRODUCT_NAME
#     FROM FOOD_PRODUCT F1
#     JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
#             FROM FOOD_PRODUCT
#             WHERE CATEGORY REGEXP '과자|국|김치|식용유'
#             GROUP BY CATEGORY) AS F2
#       ON F1.CATEGORY = F2.CATEGORY AND F1.PRICE = F2.MAX_PRICE
#     ORDER BY MAX_PRICE DESC