SELECT T.ITEM_ID, I2.ITEM_NAME, I2.RARITY
    FROM ITEM_INFO AS I
    JOIN ITEM_TREE AS T
      ON I.ITEM_ID = T.PARENT_ITEM_ID
    JOIN ITEM_INFO AS I2
      ON T.ITEM_ID = I2.ITEM_ID
    WHERE I.RARITY = 'RARE'
    ORDER BY 1 DESC
    
















# SELECT T.ITEM_ID, ITEM_NAME, RARITY
#     FROM ITEM_INFO I
#     JOIN ITEM_TREE T
#       ON I.ITEM_ID = T.ITEM_ID
#     WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
#     ORDER BY ITEM_ID DESC