WITH SEDAN_SUV_NOV AS(
    SELECT DISTINCT C.CAR_ID, CAR_TYPE, DAILY_FEE #, START_DATE, END_DATE
        FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          ON C.CAR_ID = H.CAR_ID
        WHERE CAR_TYPE REGEXP '세단|SUV' AND
                C.CAR_ID NOT IN (SELECT CAR_ID 
                                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                                WHERE NOT (END_DATE < '2022-11-01' OR
                                            '2022-11-30' < START_DATE))
)
SELECT CAR_ID, D.CAR_TYPE, FLOOR((30*DAILY_FEE*(100-DISCOUNT_RATE)/100)) AS FEE
    FROM SEDAN_SUV_NOV S
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
      ON S.CAR_TYPE = D.CAR_TYPE
    WHERE DURATION_TYPE = '30일 이상'
    HAVING FEE BETWEEN 500000 AND 2000000-1
    
    ORDER BY 3 DESC, 2, 1 DESC
    





# CAR_RENTAL_COMPANY_CAR : "자동차 ID,"" 자동차 종류", 일일 대여 요금(원), 자동차 옵션 리스트

# CAR_RENTAL_COMPANY_RENTAL_HISTORY :  자동차 대여 기록 ID, "자동차 ID", 대여 시작일, 대여 종료일

# CAR_RENTAL_COMPANY_DISCOUNT_PLAN :  할인 정책 ID, "자동차 종류", 대여 기간 종류, 할인율(%)














# SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, FLOOR(30*DAILY_FEE*(1 - DISCOUNT_RATE/100)) AS FEE
#     FROM CAR_RENTAL_COMPANY_CAR AS C
#     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
#       ON C.CAR_ID = H.CAR_ID 
#     JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
#       ON C.CAR_TYPE = D.CAR_TYPE AND
#          D.DURATION_TYPE = '30일 이상'
#     WHERE C.CAR_TYPE IN ('세단', 'SUV') 
#           AND C.CAR_ID NOT IN (SELECT CAR_ID 
#                                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                                 WHERE NOT (END_DATE < '2022-11-01' OR 
#                                            '2022-11-30' < START_DATE))
#     HAVING FEE BETWEEN 500000 AND 2000000-1
#     ORDER BY 3 DESC, 2, 1 DESC;