# WITH 세단_SUV AS(
#     SELECT C.CAR_ID, C.CAR_TYPE, (DAILY_FEE*30) AS FEE, START_DATE, END_DATE
#         FROM CAR_RENTAL_COMPANY_CAR AS C
#         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
#           ON C.CAR_ID = H.CAR_ID 
#         WHERE C.CAR_TYPE IN ('세단', 'SUV') 
#           AND ((END_DATE < '2022-11-01') OR ('2022-11-30' < START_DATE))
# )
# SELECT DISTINCT CAR_ID, C.CAR_TYPE, CAST((FEE*(100-DISCOUNT_RATE)/100) AS SIGNED) AS FEE
#     FROM 세단_SUV AS C
#     JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
#       ON C.CAR_TYPE = D.CAR_TYPE AND
#          D.DURATION_TYPE = '30일 이상'
#     HAVING FEE BETWEEN 500000 AND 2000000
#     ORDER BY 3 DESC, 2, 1 DESC;

SELECT 
    c.CAR_ID,
    c.CAR_TYPE,
    FLOOR(c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR c
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON 
    c.CAR_TYPE = p.CAR_TYPE
AND 
    p.DURATION_TYPE = '30일 이상'
WHERE 
    c.CAR_TYPE IN ('세단', 'SUV')
    AND c.CAR_ID NOT IN (
        SELECT DISTINCT r.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY r
        WHERE NOT (
            r.END_DATE < '2022-11-01' OR 
            r.START_DATE > '2022-11-30'
        )
    )
    AND FLOOR(c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30) BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC,
    c.CAR_TYPE ASC,
    c.CAR_ID DESC;
