SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, POSITION, EMAIL
    FROM HR_DEPARTMENT AS D, HR_EMPLOYEES AS E, HR_GRADE AS G
    WHERE D.DEPT_ID = E.DEPT_ID AND E.EMP_NO = G.EMP_NO AND G.YEAR = 2022
    GROUP BY G.EMP_NO
    ORDER BY 1 DESC
    LIMIT 1


# D : 부서 ID, 국문 부서명, 영문 부서명, 부서 위치
# E : 사번, 성명, 부서 ID, 직책, 이메일, 전화번호, 입사일, 연봉
# G : 사번, 연도, 반기, 평가 점수













# SELECT SUM(SCORE) AS SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
#     FROM HR_EMPLOYEES E
#     JOIN HR_GRADE G
#       ON E.EMP_NO = G.EMP_NO
#     WHERE YEAR = 2022
#     GROUP BY E.EMP_NO
#     ORDER BY 1 DESC
#     LIMIT 1