SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, 
        ID
    FROM ECOLI_DATA
    
    
    ORDER BY 1, 2

















# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
#         MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, 
#         ID
#     FROM ECOLI_DATA 
#     ORDER BY 1, 2
    


















# # SELECT B.YEAR AS YEAR, 
# #         MAX_SIZE-A.SIZE_OF_COLONY AS YEAR_DEV, 
# #         ID
# #     FROM ECOLI_DATA A, ( SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
# #                             FROM ECOLI_DATA
# #                             GROUP BY YEAR ) B
# #     WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
# #     ORDER BY 1, 2