SELECT P.PRODUCT_CODE, (P.PRICE * SUM(S.SALES_AMOUNT)) AS SALES
    FROM PRODUCT AS P, OFFLINE_SALE AS S
    WHERE P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY S.PRODUCT_ID
    ORDER BY 2 DESC, 1





# P : 상품 ID, 상품코드, 판매가

# S :  판매 ID, 상품 ID, 판매량, 판매일










# SELECT PRODUCT_CODE, PRICE*SUM(SALES_AMOUNT) AS SALES
#     FROM PRODUCT A 
#     JOIN OFFLINE_SALE B
#       ON A.PRODUCT_ID = B.PRODUCT_ID
#     GROUP
#        BY A.PRODUCT_ID
#     ORDER
#        BY SALES DESC, PRODUCT_CODE;