SELECT CONCAT(FLOOR((MONTH(DIFFERENTIATION_DATE)-1)/3)+1,'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    GROUP BY 1
    ORDER BY 1

# 대장균 개체의 ID, 부모 개체의 ID, 개체의 크기, 분화되어 나온 날짜, 개체의 형질











# SELECT CASE
#         WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
#         WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
#         WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
#         ELSE '4Q' 
#     END AS QUARTER, COUNT(*) AS ECOLI_COUNT
#     FROM ECOLI_DATA
#     GROUP BY 1
#     ORDER BY 1