SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
    FROM SKILLCODES AS S
    JOIN DEVELOPERS AS D
      ON S.CODE & D.SKILL_CODE
    WHERE NAME = 'C#' OR NAME = 'Python'
    ORDER BY 1















# SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
#     FROM DEVELOPERS D
#     JOIN SKILLCODES S
#       ON D.SKILL_CODE & S.CODE
#     WHERE NAME = 'Python' OR NAME = 'C#'
#     ORDER BY 1