WITH TRUCKS AS(
    SELECT C.CAR_ID, CAR_TYPE, 
            HISTORY_ID, DAILY_FEE, 
            DATEDIFF(END_DATE, START_DATE)+1 AS DURATION,
            CASE
                WHEN DATEDIFF(END_DATE, START_DATE)+1<7 THEN '없음'
                WHEN DATEDIFF(END_DATE, START_DATE)+1<30 THEN '7일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE)+1<90 THEN '30일 이상'
                ELSE '90일 이상'
            END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          ON C.CAR_ID = H.CAR_ID
        WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, CAST((DAILY_FEE * DURATION)*(1-(IFNULL(D.DISCOUNT_RATE,0)/100)) AS SIGNED) AS FEE
        # CASE
        #     WHEN DISCOUNT_RATE IS NULL THEN DAILY_FEE * DURATION
        #     ELSE CAST((DAILY_FEE * DURATION)*(1-(D.DISCOUNT_RATE/100)) AS SIGNED)
        # END AS FEE
    FROM TRUCKS T
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
      ON (T.CAR_TYPE = D.CAR_TYPE) AND (T.DURATION_TYPE = D.DURATION_TYPE)
    
    ORDER BY 2 DESC, 1 DESC;