SELECT
    FOOD_TYPE
    , REST_ID
    , REST_NAME
    , FAVORITES
FROM (SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, 
            MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) MAX_FAV
        FROM REST_INFO) S
WHERE FAVORITES = MAX_FAV
ORDER BY 1 DESC















# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
#     FROM REST_INFO
#     WHERE FAVORITES = (SELECT MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) FROM REST_INFO)
#     GROUP BY 1
#     ORDER BY 1 DESC














# # # SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# # #     FROM REST_INFO
# # #     WHERE FAVORITES IN (SELECT MAX(FAVORITES)
# # #             FROM REST_INFO
# # #             GROUP BY FOOD_TYPE)
# # #     GROUP BY FOOD_TYPE
# # #     ORDER BY FOOD_TYPE DESC