WITH RECURSIVE GENERATION AS(
    SELECT ID, PARENT_ID, 1 AS LV
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, G.LV + 1
        FROM ECOLI_DATA E
        INNER JOIN GENERATION G
        ON E.PARENT_ID = G.ID
)
SELECT ID
    FROM GENERATION
    WHERE LV = 3
    ORDER BY ID
    