WITH SUB AS(
    SELECT H.FLAVOR AS FLAVOR, (H.TOTAL + J.TOTAL) AS TOTAL
        FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
                FROM FIRST_HALF
                GROUP BY 1) AS H
        JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
                FROM JULY
                GROUP BY 1) AS J
          ON H.FLAVOR = J.FLAVOR
)
SELECT FLAVOR
    FROM SUB 
    ORDER BY TOTAL DESC
    LIMIT 3
    
    



















# SELECT F.FLAVOR
#     FROM FIRST_HALF F
#     JOIN JULY J
#       ON F.FLAVOR = J.FLAVOR
#     GROUP BY F.FLAVOR
#     ORDER BY (F.TOTAL_ORDER + SUM(J.TOTAL_ORDER)) DESC
#     LIMIT 3